CC = c++
FLAGS = -Wall -Werror -Wextra -std=c++98
SRC = Fixed.cpp main.cpp
OBJ = $(SRC:.cpp=.o)
RM = rm -f
NAME = fixed

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean:
	$(RM) $(OBJ) $(NAME)

re:
	clean
	rm -f $(NAME)

.PHONY: all clean fclean re

